name: unicomapps
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  inspireui: 1.1.6

  # Base
  intl: 0.17.0
  crypto: 3.0.2
  path_provider: 2.0.11
  url_launcher: 6.1.5
  localstorage: 4.0.0+1
  http: 0.13.5
  http_auth: 1.0.1
  share: 2.0.4
  tuple: 2.0.0
  shared_preferences: 2.0.15
  collection: 1.16.0
  quiver: 3.1.0
  async: 2.8.2
  html: 0.15.0
  vector_math: 2.1.2
  path: 1.8.1
  flutter_svg: 1.1.2

  expandable: ^5.0.1
  # FIREBASE PACKAGES
  firebase_core: 1.20.0
  firebase_analytics: 9.3.0
  firebase_auth: 3.6.2
  firebase_remote_config: 2.0.13
  firebase_dynamic_links: 4.3.3
  cloud_firestore: 3.4.3

  # Additional Firebase packages. To prevent unexpected upgrade.
  firebase_core_platform_interface: 4.5.0
  firebase_analytics_platform_interface: 3.3.0
  firebase_auth_platform_interface: 6.5.2
  firebase_dynamic_links_platform_interface: 0.2.3+8
  firebase_messaging_platform_interface: 4.1.0
  firebase_remote_config_platform_interface: 1.1.12

  # PUSH NOTIFICATION
  firebase_messaging: 12.0.1
  notification_permissions: 0.6.1
  flutter_local_notifications: 9.7.0
  onesignal_flutter: 3.4.0

  # STATE MANAGEMENT
  provider: 6.0.3
  get_it: 7.2.0

  # SPLASH SCREEN, ONBOARD
  lottie: 1.4.0
  rive: 0.9.1

  # WEB TOOLS
  html_unescape: 2.0.0
  webview_flutter: 3.0.4
  webview_flutter_web: 0.1.0+4
  responsive_builder: 0.4.2
  flutter_inappwebview: 5.4.3+7

  # HTML render
  flutter_widget_from_html_core: 0.8.5+3
  fwfh_svg: 0.7.2
  fwfh_cached_network_image: 0.7.0+2
  fwfh_url_launcher: 0.6.1+3
  fwfh_chewie: 0.7.0+1

  # MAP
  google_maps_flutter: 2.1.10
  geocode: 1.0.2
  location: 4.4.0

  # AUTHENTICATION
  the_apple_sign_in: 1.1.1
  flutter_facebook_auth: 4.4.0+1
  google_sign_in: 5.4.0
  sms_autofill: 2.2.0

  # PERMISSION
  # Don't upgrade permission_handler to 10+ version. file_picker is not ready for Android 13.
  permission_handler: 9.2.0

  # FILES, IMAGES
  file_picker: 5.0.1
  cached_network_image: 3.2.1
  image: 3.2.0
  transparent_image: 2.0.0
  image_picker: 0.8.5+3
  flutter_native_image: 0.0.6+1
  flutter_cache_manager: 3.3.0
  wechat_assets_picker: 7.3.4
  photo_manager: 2.1.4
  geolocator: ^9.0.2

  # TOOLS
  google_fonts: 3.0.1
  random_string: 2.3.1
  json_annotation: 4.6.0
  timeago: 3.2.2
  universal_platform: 1.0.0+1
  uuid: 3.0.6
  easy_debounce: 2.0.2+1
  devicelocale: 0.5.2 # update new version require new compileSdkVersion
  visibility_detector: 0.3.3
  rate_my_app: 1.1.3
  flutter_linkify: 5.0.2
  gms_check: 1.0.0
  new_version: 0.3.1
  video_player: 2.4.5
  in_app_update: 3.0.0
  google_mobile_ads: 2.0.0

  # UI
  flutter_spinkit: 5.1.0
  smooth_page_indicator: 1.0.0+2
  animated_text_kit: 4.2.2
  flash: 2.0.3+3
  flutter_staggered_grid_view: 0.6.2
  pin_code_fields: 7.4.0
  country_code_picker: 2.0.2
  country_pickers: 2.0.0
  dropdown_search: 5.0.2
  intro_slider: 3.0.9
  flutter_zoom_drawer: 3.0.3
  extended_image: 6.2.1
  dotted_decoration: 2.0.0
  awesome_card: 1.1.7
  maps_launcher: 2.0.1
  qr_code_scanner: 1.0.0
  flutter_calendar_carousel: 2.4.0
  flutter_otp_text_field: ^1.1.1
  fluttertoast: ^8.1.1



  ### Native Payment
  razorpay_flutter: 1.3.2
  paytm_allinonesdk: 1.1.7
  #flutter_paystack:
   # git: https://github.com/inspireui/flutter_paystack
  flutterwave_standard: 1.0.4

  ### Flutter 3 fix warning
  charts_flutter:
    git:
      url: https://github.com/inspireui/charts.git
      path: charts_flutter
  fwfh_webview:
    git:
      url: https://github.com/inspireui/flutter_widget_from_html.git
      ref: 1f471412850b2c5e558273e8e9a7900b389cf4a6
      path: packages/fwfh_webview
  flutter_swiper_null_safety:
    git: https://github.com/inspireui/flutter_swiper_null_safety
  flare_flutter:
    git:
      url: https://github.com/inspireui/Flare-Flutter.git
      ref: fd4bcba22aae4c028286e453deeb78f3311e689a
      path: flare_flutter
  pull_to_refresh:
    git: https://github.com/inspireui/flutter_pulltorefresh

  ###---- Some extra featureen is disable by default -----###
  ### 💳 Facebook Ads
  ### Search "Enable Facebook Ads" & uncomment to use  - https://tppr.me/9Pkf9
  # facebook_audience_network: 1.0.0-nullsafety.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/appFiles/config/
    - lib/appFiles/config/states/
    - lib/appFiles/config/stories/
    - assets/icons/brands/
    - assets/icons/credit_cards/
    - assets/icons/tabs/
    - assets/icons/payment/
    - assets/icons/logins/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/html/
    - google_fonts/
